services:
  fitnessapp:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DOTNET_USER_SECRETS=${DOTNET_USER_SECRETS:-$HOME/.microsoft/usersecrets}
      - DOTNET_HTTPS_CERTS=${DOTNET_HTTPS_CERTS:-$HOME/.aspnet/https}
      - ASPNETCORE_URLS=http://+:8080;
    ports:
      - "8080:8080"
