services:
  fitnessapp:
    image: ${DOCKER_REGISTRY-}fitnessapp
    build:
      context: .
      dockerfile: FitnessApp/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      Jwt__Key: ${JWT_KEY}
      ConnectionStrings__DefaultConnection: ${CONNECTION_STRING}
    ports:
      - "8080:8080"
      - "8081:8081"
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
