services:
  fitnessapp:
    image: ${DOCKER_REGISTRY-}fitnessapp
    build:
      context: .
      dockerfile: FitnessApp/Dockerfile
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
